---
title: "p8105_hw5_zq2209"
author: "Zining Qi"
date: "2022-11-14"
output: github_document
---

```{r}
library(tidyverse)
```


# Problem 2
```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicide = read_csv(url) %>% 
  janitor::clean_names()
```

```{r}
summary(homicide)
```

```{r}
homicide$city_state = paste(homicide$city, homicide$state, sep = ', ')
```


```{r}
total_homicides_cities = homicide %>% 
  group_by(city_state) %>% 
  summarize(total = n())
```

```{r}
total_unsolved_homicides = homicide %>% 
  filter(disposition == 'Closed without arrest' | disposition == 'Open/No arrest') %>% 
  group_by(city_state) %>% 
  summarize(unsolved = n())
```

```{r}
total_homicides = left_join(total_homicides_cities, total_unsolved_homicides, by = "city_state")
total_homicides
```

```{r}
total_homicides_baltimore = total_homicides %>% 
  filter(city_state == "Baltimore, MD")
prop.test_baltimore = prop.test(total_homicides_baltimore$unsolved, total_homicides_baltimore$total)
```


```{r}
prop_test = function(df) {
  ci_unsolved <- prop.test(df$unsolved, df$total)
  broom::tidy(ci_unsolved) %>% 
    select(estimate, conf.low, conf.high)
}
```


```{r}
prop_test_baltimore = total_homicides %>% 
  filter(city_state == "Baltimore, MD") %>% 
  prop_test() %>% 
  rename("Estimate of proportion" = estimate, 
         "Lower bound" = conf.low, 
         "Upper bound" = conf.high) %>% 
  knitr::kable()
```

```{r}
city_nest = nest(total_homicides, unsolved:total)
city_nest$data[[1]]
```

```{r}

```

```{r}
prop_test_all = city_nest[-49,] %>% 
  mutate(prop_unsolved = map(data, prop_test)) %>% 
  unnest() %>% 
  rename('Estimate of proportion' = estimate, 
         "Lower bound" = conf.low, 
         "Upper bound" = conf.high) %>% 
  knitr::kable()
prop_test_all
```

```{r}
prop_ci_all = city_nest[-49,] %>% 
  mutate(prop_unsolved = map(data, prop_test)) %>% 
  unnest()
prop_ci_all %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point(color = "red") + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  coord_flip() + 
  labs(title = "Proportion of unsolved cases in 50 major US cities", 
       y = "Proportion of unsolved cases", 
       x = "City", 
       caption = "Bars represent 95% confidence interval") + 
  theme_classic() 
```


# Problem 3

```{r}
datasets = map(1:5000, ~ rnorm(n = 30, mean = 0, sd = 5))
```

```{r}
t_test = function(mu = 0) {
  sample = tibble(rnorm(n = 30, mean = mu, sd = 5))
  
  result = t.test(sample) %>% 
    broom::tidy() %>% 
    select(estimate,p.value)
  
  result
}
```

```{r}
t_test(mu = 0) %>% 
  knitr::kable()
```

```{r}
t_test_mu0 = expand_grid(mean = 0, iteration = 1:5000) %>%
  mutate(result = map(mean,t_test)) %>% 
  unnest(result)
head(t_test_mu0)
```

```{r}
t_test_all <- expand_grid(mean = 1:6, iteration = 1:5000) %>% 
  mutate(result = map(mean,t_test)) %>% 
  unnest(result)

head(t_test_all)
```

```{r}
t_test_all %>%
  group_by(mean) %>% 
  summarize(reject_prop = sum(p.value < 0.05)/5000) %>% 
  ggplot(aes(x = mean,y = reject_prop)) +
  scale_x_continuous(limits = c(1,6), breaks = seq(1,6,1)) + 
  geom_point() + geom_path() +
  labs(x = "True Mean",y = "Power of Test",title = "Power of t.test on different means")
```

```{r}
t_test_all %>%
  group_by(mean) %>% 
  summarize(average_estimates = mean(estimate,na.rm = T)) %>% 
  ggplot(aes(x = mean,y = average_estimates)) +
  scale_x_continuous(limits = c(1,6), breaks = seq(1,6,1)) + 
  geom_point() + geom_path() +
  labs(x = "True Mean",y = "Average of Estimated Means for all Samples",title = "Estimated Means")
```

```{r}
t_test_reject <- t_test_all %>% 
  filter(p.value < 0.05) %>% 
  group_by(mean) %>% 
  summarize(average_estimates = mean(estimate,na.rm = T)) %>% 
  ungroup()

t_test_all = t_test_all %>% 
  group_by(mean) %>% 
  summarize(average_estimates = mean(estimate,na.rm = T)) %>% 
  ungroup()
```

```{r}
t_test_reject %>% 
  ggplot(aes(x = mean,y = average_estimates)) +
  scale_x_continuous(limits = c(1,6), breaks = seq(1,6,1)) + 
  geom_point() + geom_path() +
  labs(x = "True Mean",y = "Average of Estimated Means for Rejected Samples",title = "Estimated Means")
```

```{r}
ggplot(t_test_all, aes(x = mean, y = average_estimates)) +
  geom_line(data = t_test_all, aes(color = "black")) +
  geom_line(data = t_test_reject, aes(color = "red")) +
  scale_color_manual(name = " ", values = c("black" = "black", "red" = "red"),
                     labels = c('Estimates of All Samples','Estimates of Rejected Samples')) +
  geom_point(data = t_test_all,color = "black") +
  geom_point(data = t_test_reject,color = "red") +
  scale_x_continuous(limits = c(1,6), breaks = seq(1,6,1)) +
  labs(x = "True Mean",y = "Average of Estimate Means",title = "Estimates of All Samples vs. Rejected Samples")
```











